"""Vendored telemetry package for the copilot-confirm OpenClaw skill.

This package is a verbatim copy of the telemetry module from the
copilot-confirm pip package, bundled into the skill so the skill can
log v2 telemetry without requiring the pip package to be installed.

Source of truth: src/copilot_confirm/telemetry.py in the
mgrandau/copilot-confirm repo. A test in the repo
(tests/test_skill_vendored_in_sync.py) asserts byte-equality between
that file and the vendored copy here. Do not edit this file directly —
edit the source and re-vendor via `pdm run sync-skill`.
"""

from .telemetry import (
    FileSystemProtocol,
    NetworkProtocol,
    RealFileSystem,
    RealNetwork,
    TelemetryConfig,
    TelemetryEntry,
    TelemetryLogger,
    create_telemetry_logger,
    load_config,
)

__all__ = [
    "FileSystemProtocol",
    "NetworkProtocol",
    "RealFileSystem",
    "RealNetwork",
    "TelemetryConfig",
    "TelemetryEntry",
    "TelemetryLogger",
    "create_telemetry_logger",
    "load_config",
]
